easy_admin:
    site_name: 'TIN Projekt Backend'
    design:
        brand_color: '#1ABC9C'
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\AdminController
            templates:
                list: 'admin/user/list.html.twig'
            list:
                title: 'User list'
                actions:
                    - { name: 'edit', css_class: 'btn btn-sm btn-warning' }
                    - { name: 'delete', css_class: 'btn btn-sm  btn-danger' }
                fields:
                    - id
                    - name
                    - email
                    - { property: 'roles', label: 'Role', template: 'admin/user/roles.html.twig' }
            form:
                fields:
                    - name
                    - email
                    - { property: 'password', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
