#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /logout

app_dashboard:
  path: /
  controller: App\Controller\HomeController::indexAction

app_event:
  path: /event/{id}
  controller: App\Controller\HomeController::eventAction